"colorscheme alpha
set shiftwidth=4
set tabstop=4
set expandtab
set autoindent
set guifont=Consolas:h11
syn on
set hlsearch
set ruler
"set backupdir=H:\vimfiles\temp
set backspace=indent,eol,start
set ignorecase
"set lines=25 columns=100


set dir=~/tmp


" Uncomment the following to have Vim jump to the last position when
" reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif
